### PR TITLE
Full translation of Simplified Chinese and Traditional Chinese

### PR DESCRIPTION
**Pull request by HaoJun0823**
I don't have a server, so I didn't test if this file can run the load, but I marked the translated text in the correct language flag and checked for no formatting errors.
"zho" is traditional Chinese, and "chi" is simplified Chinese.

I asked Russian friends and other people, everyone did not understand the meaning of "unstucking prop block", so I translated this sentence according to my own understanding.

Full translation, no errors, except for some gun names (however, it does not affect player identification).

====================================
Full translation of Simplified Chinese and Traditional Chinese.
Fixed some bugs.

### CODE REVIEW

**Comment by qubka** [comment]
unsticking prop block, says when you try to use unstuck, but you no actually stack in other physics object
I aslo added knifes for next update, can you please also translate them and I will include file in next update
`"knifegg" // Menu
    {
        "en"            "Gold Knife"
        "ru"            "Золотой нож"
    }
    
    "knife gut" // Menu
    {
        "en"            "Gut Knife"
        "ru"            "Потрошитель"
    }
    
    "knife flip" // Menu
    {
        "en"            "Flip Knife"
        "ru"            "Нож перевертыш"
    }
    
    "m9 bayonet" // Menu
    {
        "en"            "M9 Bayonet"
        "ru"            "M9 Bayonet"
    }
    
    "karambit" // Menu
    {
        "en"            "Karambit"
        "ru"            "Карамбит"
    }
    
    "knife tactical" // Menu
    {
        "en"            "Huntsman Knife"
        "ru"            "Нож егеря"
    }
    
    "knife falchion" // Menu
    {
        "en"            "Falchion Knife"
        "ru"            "Фальшион"
    }
    
    "knife butterfly" // Menu
    {
        "en"            "Butterfly"
        "ru"            "Бабочка"
    }
    
    "knife bowie" // Menu
    {
        "en"            "Bowie Knife"
        "ru"            "Охотничий нож"
    }
    
    "knife push" // Menu
    {
        "en"            "Shadow Daggers"
        "ru"            "Клинки"
    }
    
    "knife ursus" // Menu
    {
        "en"            "Ursus Knife"
        "ru"            "Бурый нож"
    }
    
    "knife gypsy" // Menu
    {
        "en"            "Navaja Knife"
        "ru"            "Навахо нож"
    }
    
    "knife stiletto" // Menu
    {
        "en"            "Stiletto Knife"
        "ru"            "Шпилька нож"
    }
    
    "knife widowmaker" // Menu
    {
        "en"            "Talon Knife"
        "ru"            "Нож коготь"
    }`

**Comment by HaoJun0823** [comment]
`"knifegg" // Menu
{
	"en" 		"Gold Knife"
	"ru" 		"Золотой нож"
	"chi"		 "黄金之刃"
	"zho"		 "黃金之刃"
}

"knife gut" // Menu
{
    "en"            "Gut Knife"
    "ru"            "Потрошитель"
	"chi"			 "穿肠刀"
	"zho" 			 "穿腸刀"
}

"knife flip" // Menu
{
    "en"            "Flip Knife"
    "ru"            "Нож перевертыш"
	"chi"			 "折叠刀"
	"zho" 			 "折疊刀"
}

"m9 bayonet" // Menu
{
    "en"            "M9 Bayonet"
    "ru"            "M9 Bayonet"
	"chi"			 "M9刺刀"
	"zho" 			 "M9刺刀"
}

"karambit" // Menu
{
    "en"            "Karambit"
    "ru"            "Карамбит"
	"chi"			 "爪子刀"
	"zho" 			 "爪子刀"
}

"knife tactical" // Menu
{
    "en"            "Huntsman Knife"
    "ru"            "Нож егеря"
	"chi"			 "猎杀刀"
	"zho" 			 "獵殺刀"
}

"knife falchion" // Menu
{
    "en"            "Falchion Knife"
    "ru"            "Фальшион"
	"chi"			 "弯刀"
	"zho" 			 "彎刀"
}

"knife butterfly" // Menu
{
    "en"            "Butterfly"
    "ru"            "Бабочка"
	"chi"			 "蝴蝶刀"
	"zho" 			 "蝴蝶刀"
}

"knife bowie" // Menu
{
    "en"            "Bowie Knife"
    "ru"            "Охотничий нож"
	"chi"			 "博伊刀"
	"zho" 			 "博伊刀"
}

"knife push" // Menu
{
    "en"            "Shadow Daggers"
    "ru"            "Клинки"
	"chi"			 "暗影匕首"
	"zho" 			 "暗影匕首"
}

"knife ursus" // Menu
{
    "en"            "Ursus Knife"
    "ru"            "Бурый нож"
	"chi"			 "乌苏斯刀"
	"zho" 			 "烏蘇斯刀"
}

"knife gypsy" // Menu
{
    "en"            "Navaja Knife"
    "ru"            "Навахо нож"
	"chi"			 "剃刀"
	"zho" 			 "剃刀"
}

"knife stiletto" // Menu
{
    "en"            "Stiletto Knife"
    "ru"            "Шпилька нож"
	"chi"			 "细木工刀"
	"zho" 			 "細木工刀"
}

"knife widowmaker" // Menu
{
    "en"            "Talon Knife"
    "ru"            "Нож коготь"
	"chi"			 "利爪刀"
	"zho" 			 "利爪刀"
}
`

If you need more, just contact me.

**Comment by HaoJun0823** [comment]
Here are some advice and repairs from my Russian partner (LOD). He pointed out some errors in Russian translation, but he is not a developer, so I leave a message to you.
-------------------------
nuke is ядерная бомба (Ядерная бомба Nuclear bomb)
buy=покупает
bought=купил
Skill ready=Способность готова
You can't buy during this round=Вы не можете покупать в течение этого раунда
Change classes=Изенить класс
Player options=Опции игрока
Buy extra items=Купить дополнительные предметы
Zombie classes=Классы зомби
Admin menu=Меню админа
Deimos=Деймос
Paralyzing ball=Парализующий шар
Rifles=Винтовки
Snipers=Снайперские винтовки
Desert eagle=Дезерт Игл
Тасер=Тазер
Galil=Галил
Chicken=Курица

**Comment by qubka** [comment]
```
"shield"
    {
        "en"            "Shield"
        "ru"            "ЩИТ"
    }

"mp5sd" // Menu
    {
        "en"            "MP5-SD"
        "ru"            "MP5-SD"
    }
```

**Comment by HaoJun0823** [comment]
`
"shield"
    {
        "en"            "Shield"
        "ru"            "ЩИТ"
        "chi"            "盾"
        "zho"           "盾"
    }

"mp5sd" // Menu
    {
        "en"            "MP5-SD"
        "ru"            "MP5-SD"
        "chi"            "MP5-SD"
        "zho"           "MP5-SD"
    }
`

**Comment by qubka** [comment]
Thanks a million, I will add new translations and fix old ones, which you mentioned

**Pull request closed without merging**
